#!/bin/sh /etc/rc.common
#-- Copyright (C) 2019 letmekillthemall <qq1034309713@live.com>

START=99

start(){
	echo "enable"
	enable=$(uci get bbr.config.enabled 2>/dev/null)
	bbr_mod_enable=$(uci get bbr.config.bbr_mod_enabled 2>/dev/null)
	if [ $enable -eq 1 ]; then
		if [ $bbr_mod_enable -eq 0 ]; then
			sleep 3
			echo "bbr" > /etc/modules.d/bbr
			sed -i '/bbr/d' /etc/sysctl.conf
			echo "net.ipv4.tcp_congestion_control=bbr" > /etc/sysctl.conf
		elif [ $bbr_mod_enable -eq 1 ]; then
			sleep 3
			echo "tcp-bbr-nanqinlang" > /etc/modules.d/bbr
			sed -i '/bbr/d' /etc/firewall.user
			echo "net.ipv4.tcp_congestion_control=tcp-bbr-nanqinlang" > /etc/sysctl.conf
		fi
		sysctl -p
		if [ $re -eq 0 ]; then
			echo $re
			sysctl -p
		fi 
	fi
}

stop(){
	echo "stop"
    enable=$(uci get bbr.config.enabled 2>/dev/null)	
    if [ $enable -ne 1 ]; then
		echo "disable"
		echo "net.ipv4.tcp_congestion_control=cubic" > /etc/sysctl.conf
		sed -i '/bbr/d' /etc/sysctl.conf
		sysctl -p
		sed -i '/cubic/d' /etc/sysctl.conf
		sysctl -p
	    if [ $re -ne 1 ]; then
			echo $re
			sysctl -p
        fi 
	fi
}

restart(){
	re=1
	stop
	start
	sysctl -p
}